# Generated by Django 4.2.5 on 2023-10-02 15:16

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^([a-zA-Z]+)((\\s)([a-zA-Z]+))*$', message='First name must be Alphabetic')])),
                ('last_name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^([a-zA-Z]+)((\\s)([a-zA-Z]+))*$', message='Last name must be Alphabetic')])),
                ('username', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^(?=[A-Za-z]{1})([a-zA-Z0-9@#_.-]){3,25}$', message='invalid username, can only contain characters in between 3-25 range. String range 3-25')])),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('is_lock', models.BooleanField(default=False)),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
