# Generated by Django 4.2.5 on 2023-11-10 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_payment_shipmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwayBill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipper_company_name', models.CharField(max_length=255)),
                ('shipper_contact_person', models.CharField(max_length=255)),
                ('shipper_reference', models.CharField(max_length=255)),
                ('shipper_address', models.CharField(max_length=255)),
                ('shipper_state', models.CharField(max_length=255)),
                ('shipper_city', models.CharField(max_length=255)),
                ('shipper_post_code', models.IntegerField()),
                ('shipper_mobile_number', models.IntegerField()),
                ('shipper_phone_number', models.IntegerField()),
                ('shipper_ntn_cnic', models.CharField(max_length=255)),
                ('shipper_email_address', models.EmailField(max_length=255)),
                ('reciever_company_name', models.CharField(max_length=255)),
                ('reciever_contact_person', models.CharField(max_length=255)),
                ('reciever_address', models.CharField(max_length=255)),
                ('reciever_country', models.CharField(max_length=255)),
                ('reciever_state', models.CharField(max_length=255)),
                ('reciever_city', models.CharField(max_length=255)),
                ('reciever_post_code', models.IntegerField()),
                ('reciever_mobile_number', models.IntegerField()),
                ('reciever_phone_number', models.IntegerField()),
                ('reciever_email', models.EmailField(max_length=255)),
                ('reciever_fax', models.CharField(max_length=255)),
                ('fedex_number', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('pieces', models.IntegerField()),
                ('data', models.JSONField(null=True)),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.payment')),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.service')),
                ('shipment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.shipmenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
