# Generated by Django 4.2.5 on 2023-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_airwaybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybill',
            name='tracking_number',
            field=models.IntegerField(default=1),
        ),
    ]
