# Generated by Django 4.2.5 on 2023-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_airwaybill_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybill',
            name='tracking_number',
            field=models.IntegerField(default=0),
        ),
    ]
