# Generated by Django 4.2.5 on 2023-11-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_airwaybill_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybill',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
