# Generated by Django 4.2.5 on 2023-11-27 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_airwaybill_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwayBillLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('airway_bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.airwaybill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
