# Generated by Django 5.0.1 on 2024-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_airwaybilllocation_airway_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybill',
            name='reciever_mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='airwaybill',
            name='reciever_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='airwaybill',
            name='shipper_mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='airwaybill',
            name='shipper_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
