# Generated by Django 5.0.1 on 2024-01-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_airwaybill_reciever_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airwaybill',
            name='fedex_number',
        ),
        migrations.RemoveField(
            model_name='airwaybill',
            name='reciever_fax',
        ),
        migrations.RemoveField(
            model_name='airwaybill',
            name='shipper_email_address',
        ),
    ]
