# Generated by Django 5.0.1 on 2024-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_remove_airwaybill_fedex_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybill',
            name='eori_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airwaybill',
            name='reciever_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
