# Generated by Django 5.0.1 on 2024-01-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_airwaybill_eori_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybill',
            name='reciever_post_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airwaybill',
            name='shipper_post_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
