# Generated by Django 5.0.1 on 2024-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_airwaybill_reciever_post_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybilllocation',
            name='description',
            field=models.CharField(blank=True, default='In progress', max_length=400),
        ),
    ]
