# Generated by Django 5.0.1 on 2024-03-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_airwaybilllocation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybilllocation',
            name='description',
            field=models.CharField(blank=True, default='In progress', max_length=400, null=True),
        ),
    ]
