# Generated by Django 5.0.1 on 2024-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_airwaybilllocation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybilllocation',
            name='position',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
