# Generated by Django 5.0.1 on 2024-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_airwaybilllocation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airwaybill',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
